### ISSUE TITLE
Installation of FabNEPTUNE plug-in fails with a `KeyError`

### ISSUE THREAD

**Issue by matt-graham** [UCL-CCS/FabNEPTUNE#1]
Running

```console
fabsim localhost install_plugin:FabNEPTUNE
```

to install the FabNEPTUNE plug-in in FabSIM as suggested in the documentation results in a `KeyError: 'FabNEPTUNE'` exception with traceback

```
Traceback (most recent call last):
  File "FabSim3/fabsim/bin/fabsim", line 46, in <module>
    sys.exit(fabsim_main.main())
  File "FabSim3/fabsim/base/fabsim_main.py", line 150, in main
    env.exec_func(*env.task_args, **env.task_kwargs)
  File "FabSim3/fabsim/base/decorators.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "FabSim3/fabsim/base/setup_fabsim.py", line 29, in install_plugin
    info = config[plugin_name]
```

for me presumably as there is not currently a FabNEPTUNE entry in this [`plugins.yml` file](https://github.com/djgroen/FabSim3/blob/master/fabsim/deploy/plugins.yml)? Adding an entry

```YAML
FabNEPTUNE:
  repository: https://github.com/UCL-CCS/FabNEPTUNE.git
```

to the `plugins.yml` file in a local clone of `FabSim3` and rerunning installation seems to work. I've raised this issue in this repository in case it is something that should be fixed in the documentation here, but as it looks like the fix might need to be performed on the FabSim3 side it might make more sense to transfer this issue there.

**Comment by kbronik2017** [comment]
Thank you for pointing that out, I was aware of that, and asked  Derek to update Fabsim3, there won't be an issue in the new version of Fabsim3 regarding the Installation of FabNEPTUNE plug-in
