### ISSUE TITLE
sbatch warning: working directory is /home directory on ARCHER2

### ISSUE THREAD

**Issue by yyimingucl** [UCL-CCS/FabNEPTUNE#2]
Hi all, 

I am running the Convection2D_remote:convection_2d_test on ARCHER2 by following the FabNEPTUNE Documentations. The Job could be submitted successfully but sbatch returns a warning that `It appears your working directory may not be on the work filesystem It is /home directory.` 

One thing I found in env.log is that `SLURM_SUBMIT_DIR=/home2/home/e723/e723/yiming`. But I have no clue where the configuration appears.  

The attached file is terminal warning.

Many thanks for any help and suggestions.
<img width="857" alt="terminal_warning" src="https://user-images.githubusercontent.com/57998874/166431298-c7094fa5-a324-4cde-9290-3caa2a676657.png">

**Comment by kbronik2017** [comment]
Hi Yiming,

This is a known warning (which  can be ignored), however, to get rid of this warning you can do the following:
Open FabSim3/fabsim/deploy/machines.yml and add the "cd /mnt/lustre/a2fs-work2/work/yours;" to job_dispatch, for example it might look like:

archer2:
  remote: "login.archer2.ac.uk"
  project: "e723-SEAVEA"
  qos_name: "standard"
  stat: "squeue -u $username"
  ...
  job_dispatch: "cd /mnt/lustre/a2fs-work2/work/e723/e723/kevinb;  sbatch"
  ....
  
The reason for this warning is: In general, fabsim submission look like:

sshpass -p 'xxxxxxxxxx' ssh kevinb@login.archer2.ac.uk 'sbatch /work/e723/e723/kevinb/FabSim/results/convection_3d_testX_archer2_128/convection_3d_testX_archer2_128.sh'

and you will see a warning, while doing the above modification and then submitting, the fabsim submission will look like:

sshpass -p 'xxxxxxxxxx' ssh kevinb@login.archer2.ac.uk 'cd /mnt/lustre/a2fs-work2/work/e723/e723/kevinb; sbatch /work/e723/e723/kevinb/FabSim/results/convection_3d_testX_archer2_128/convection_3d_testX_archer2_128.sh'

and you won't see any warning

**Comment by yyimingucl** [comment]
Thanks Kevin

**Comment by kbronik2017** [comment]
My pleasure!
